#include "HyprlandLuaConfig.hpp"
#include <QFile>
#include <QDebug>
#include <QRegularExpression>

namespace keyoubs {

HyprlandLuaConfig::HyprlandLuaConfig(QObject *parent)
    : QObject(parent)
{
}

bool HyprlandLuaConfig::loadFromFile(const QString &path)
{
    QFile file(path);
    if (!file.open(QIODevice::ReadOnly)) {
        emit parseError("Cannot open file: " + path, 0);
        return false;
    }
    return loadFromString(QString::fromUtf8(file.readAll()));
}

bool HyprlandLuaConfig::loadFromString(const QString &luaContent)
{
    m_configData.clear();

    // Simple parser for hl.* API calls
    // e.g., hl.general.gaps_in = 5
    // e.g., hl.monitor = {{ name = "DP-1", width = 1920 }}

    QRegularExpression re(R"((\w+(?:\.\w+)*)\s*=\s*(.+))");
    QRegularExpressionMatchIterator it = re.globalMatch(luaContent);

    while (it.hasNext()) {
        QRegularExpressionMatch match = it.next();
        QString key = match.captured(1);
        QString valueStr = match.captured(2).trimmed();

        // Remove trailing comma if present
        if (valueStr.endsWith(',')) {
            valueStr.chop(1);
        }

        QVariant value = parseLuaValue(valueStr, 0);
        m_configData[key] = value;
    }

    emit configLoaded(m_configData);
    return true;
}

bool HyprlandLuaConfig::saveToFile(const QString &path) const
{
    QFile file(path);
    if (!file.open(QIODevice::WriteOnly)) {
        return false;
    }
    file.write(toLuaString().toUtf8());
    emit const_cast<HyprlandLuaConfig*>(this)->configSaved(path);
    return true;
}

QString HyprlandLuaConfig::toLuaString() const
{
    QString out;
    out += "-- Generated by Keyoubs\n";
    out += "-- Hyprland Lua config\n\n";

    for (auto it = m_configData.begin(); it != m_configData.end(); ++it) {
        out += it.key() + " = ";
        writeLuaValue(out, it.value(), 0);
        out += "\n";
    }

    return out;
}

QString HyprlandLuaConfig::migrateFromHyprlang(const QString &confContent)
{
    QStringList lines = confContent.split('\n');
    QString luaOut;
    luaOut += "-- Migrated from hyprland.conf by Keyoubs\n\n";

    for (const QString &line : lines) {
        QString trimmed = line.trimmed();
        if (trimmed.isEmpty() || trimmed.startsWith('#')) {
            luaOut += line + "\n";
            continue;
        }

        // Simple conversion: key = value → hl.key = value
        // This is a simplified migration — real Hyprlang has sections
        if (trimmed.contains('=')) {
            int eqPos = trimmed.indexOf('=');
            QString key = trimmed.left(eqPos).trimmed();
            QString value = trimmed.mid(eqPos + 1).trimmed();

            // Remove trailing semicolon
            if (value.endsWith(';')) {
                value.chop(1);
            }

            luaOut += "hl." + key + " = " + value + "\n";
        } else {
            luaOut += "-- " + line + "\n";
        }
    }

    return luaOut;
}

bool HyprlandLuaConfig::isLuaConfig(const QString &filePath)
{
    return filePath.endsWith(".lua");
}

bool HyprlandLuaConfig::isHyprlangConfig(const QString &filePath)
{
    return filePath.endsWith(".conf");
}

QString HyprlandLuaConfig::detectActiveFormat(const QString &configDir)
{
    QString luaPath = configDir + "/hyprland.lua";
    QString confPath = configDir + "/hyprland.conf";

    if (QFile::exists(luaPath)) {
        return "lua";
    }
    if (QFile::exists(confPath)) {
        return "hyprlang";
    }
    return "unknown";
}

QVariant HyprlandLuaConfig::parseLuaValue(const QString &content, int pos)
{
    QString trimmed = content.trimmed();

    // Number
    bool ok;
    double num = trimmed.toDouble(&ok);
    if (ok) return num;

    // Boolean
    if (trimmed == "true") return true;
    if (trimmed == "false") return false;

    // String
    if (trimmed.startsWith('"') && trimmed.endsWith('"')) {
        return trimmed.mid(1, trimmed.length() - 2);
    }

    // Table
    if (trimmed.startsWith('{')) {
        return parseLuaTable(content, pos);
    }

    // Default: return as string
    return trimmed;
}

QVariantMap HyprlandLuaConfig::parseLuaTable(const QString &content, int pos)
{
    Q_UNUSED(pos)
    QVariantMap table;

    // Very simplified table parser
    // Assumes format: { key = value, key = value }
    QString inner = content.trimmed();
    if (inner.startsWith('{')) inner = inner.mid(1);
    if (inner.endsWith('}')) inner.chop(1);

    QStringList pairs = inner.split(',');
    for (const QString &pair : pairs) {
        QString trimmed = pair.trimmed();
        if (trimmed.isEmpty()) continue;

        int eqPos = trimmed.indexOf('=');
        if (eqPos > 0) {
            QString key = trimmed.left(eqPos).trimmed();
            QString value = trimmed.mid(eqPos + 1).trimmed();

            // Remove quotes from key
            if (key.startsWith('"') && key.endsWith('"')) {
                key = key.mid(1, key.length() - 2);
            }

            int dummy = 0;
            table[key] = parseLuaValue(value, dummy);
        }
    }

    return table;
}

void HyprlandLuaConfig::writeLuaValue(QString &out, const QVariant &value, int indent) const
{
    Q_UNUSED(indent)

    switch (value.typeId()) {
    case QMetaType::QString:
        out += "\"" + value.toString() + "\"";
        break;
    case QMetaType::Int:
    case QMetaType::Double:
        out += value.toString();
        break;
    case QMetaType::Bool:
        out += value.toBool() ? "true" : "false";
        break;
    case QMetaType::QVariantMap:
        writeLuaTable(out, value.toMap(), indent);
        break;
    default:
        out += value.toString();
    }
}

void HyprlandLuaConfig::writeLuaTable(QString &out, const QVariantMap &table, int indent) const
{
    Q_UNUSED(indent)
    out += "{\n";

    for (auto it = table.begin(); it != table.end(); ++it) {
        out += "    " + it.key() + " = ";
        writeLuaValue(out, it.value(), indent + 1);
        out += ",\n";
    }

    out += "}";
}

} // namespace keyoubs
